### ISSUE TITLE
Issue with broken charts?

### ISSUE THREAD

**Issue by jondkelley** [rulerofthedeities/BPR#1]
Hi there,

I don't know which commit brought this in, but noticed the charts aren't showing the X plot with dates properly (I deployed master to my own herokuapp). All datapoints are stacked on the Y axis at the beginning when I uploaded this to heroku for a test deployment.

Still messing with the code (but JS isn't my language) to try to isolate where this is happening. Perhaps it's when you changed the `var`s to `let`s but that just changes the scope of variables so that doesn't seem to be it.

**Comment by jondkelley** [comment]
Rolling the app back to

```
commit 7245c6f71c1ad358182593121be248ae06bac3d1
Implemented Babel / Fixed datetime update
```

Seems to fix the chart date rendering issue

2100bcc3216264ad3fca2f9eb7e2a16c48794e5e  OK
272d19bf6ea279c0aec85c480f87348b0669a081 OK

**Comment by rulerofthedeities** [comment]
I checked the latest version and what I believe you're seeing is the result of how d3/c3 handles multiple data points with the same x value. So when I removed the latest entry on the heroku demo app, which was entered at the same time as the previous one, it displayed the chart as expected.
I believe the issue is caused because I use a spline chart type. I'll look into it.

**Comment by rulerofthedeities** [comment]
I changed the line types from 'spline' to 'line'. Let me know if that looks better.

**Comment by jondkelley** [comment]
Had a chance to check . Sadly this wasn't the issue. :(

If you're curious about the render here's what I'm talking about.
![errt](http://i.imgur.com/DlXd54F.png)

**Comment by jondkelley** [comment]
I'm thinking this was when index position was reordered for `dataSet = ['x', 'SYS', 'DIA', 'Pulse'];` Let me try patching back to the old dataSet behavior and see if this helps the `x` dt generation.

**Comment by jondkelley** [comment]
Yep, that's what broke. Verified by checking out 87010d655ac7a7547557b6d56d167fe7514e5f73 and then got rid of all changes that supported moving 'x' datetime element from index 3 to index 0

For example `dataSet = ['SYS', 'DIA', 'Pulse', 'x'];`
to `dataSet = ['x', 'SYS', 'DIA', 'Pulse'];`

After this change, the graph timeline renders again. This is not an issue with spline behavior as suspected earlier.

**Comment by jondkelley** [comment]
I wasn't able to find any misreferenced indexes. Everything seems to reference `ChartData[0]` to reflect `'x'`'s new location I did find browser console errors that look like `SYS` bloodpressure samples are loading as `Date` objects and failing. I can't find the misreferenced date index for the life of me though!!

`Failed to parse x '150' to Date objecti.parseDate @ vendor.js:29069
vendor.js:29069 Failed to parse x '145' to Date objecti.parseDate @ vendor.js:29069`

**Comment by jondkelley** [comment]
Pull request created to fix this in pull https://github.com/rulerofthedeities/BPR/pull/2
